// Generated by CoffeeScript 1.3.1
(function() {
  var app, everyauth, exp,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  exp = require('express');
  var routes = require('./routes')

  app = exp.createServer();

  everyauth = require('everyauth');

  everyauth.twitter.consumerKey('txEsSAyAdBVp1UJXz10Hg').consumerSecret('gi0QzE3l7ShhPpwuh8bNRj4JeMOn5i3tatg41F0aw').findOrCreateUser(function(session, token, secret, user) {
    var promise;
    return promise = this.Promise().fulfill(user);
  }).redirectPath('/');

  app.configure(function() {
    app.set('views', __dirname + '/views');
    app.set('view engine', 'jade');
    app.use(exp.bodyParser());
    app.use(exp.methodOverride());
    app.use(exp.cookieParser());
    app.use(exp.session({
      secret: 'bobsyouruncle'
    }));
    app.use(everyauth.middleware());
    app.use(app.router);
    app.use(exp.static(__dirname + '/public'));
  });

  app.listen(8080);

  console.log('Server running at http://localhost:8080');

  app.get('/', routes.index);

}).call(this);
