// Generated by CoffeeScript 1.3.1
(function() {
  var a, fn, fn2;

  fn = function(x) {
    console.log("#" + x + "#");
    return this;
  };

  fn2 = function(x) {
    console.log("*" + x + "*");
    return this;
  };

  a = {
    b: {
      d: fn2,
      e: fn2
    },
    c: fn,
    f: fn
  };

  a.b.d("d").e("e");

  a.b.d("d").e("e");

}).call(this);
